//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipt_Project_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer_table
    {
        public string employer_id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Company_name { get; set; }
        public string Company_contact_number { get; set; }
        public string Phone_number { get; set; }
    }
}
