//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipt_Project_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_postTable
    {
        public string Job_id { get; set; }
        public string Job_description { get; set; }
        public string Designation { get; set; }
        public string Employer_id { get; set; }
        public string Applicants_id { get; set; }
    }
}
